### ISSUE TITLE
[BUG] Unable to run taiga-back and taiga-async

### ISSUE THREAD

**Issue by johnyc90** [kaleidos-ventures/taiga-docker#142]
**Describe the bug**

 When run using podman + podman/docker compose, the containers run from the image taiga-back fail with the following messages:

__default entrypoint__:
```
Traceback (most recent call last):
  File "/taiga-back/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/venv/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/taiga-back/taiga/base/api/__init__.py", line 43, in <module>
    from .viewsets import ModelListViewSet
  File "/taiga-back/taiga/base/api/viewsets.py", line 38, in <module>
    from . import views
  File "/taiga-back/taiga/base/api/views.py", line 124, in <module>
    class APIView(View):
  File "/taiga-back/taiga/base/api/views.py", line 128, in APIView
    authentication_classes = api_settings.DEFAULT_AUTHENTICATION_CLASSES
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/taiga-back/taiga/base/api/settings.py", line 230, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/taiga-back/taiga/base/api/settings.py", line 182, in perform_import
    return [import_from_string(item, setting_name) for item in val]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/taiga-back/taiga/base/api/settings.py", line 182, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/taiga-back/taiga/base/api/settings.py", line 194, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/taiga-back/taiga/auth/authentication.py", line 37, in <module>
    from .settings import api_settings
  File "/taiga-back/taiga/auth/settings.py", line 270, in <module>
    'SIGNING_KEY': settings.SECRET_KEY,
                   ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

__taiga-async__:

```
Give permission to taiga:taiga
Starting Celery...
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
While trying to load the module taiga.celery the following error occurred:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'taiga' has no attribute 'celery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/celery/bin/celery.py", line 57, in convert
    return find_app(value)
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/celery/app/utils.py", line 387, in find_app
    sym = imp(app)
          ^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
    return imp(module, package=package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/taiga-back/taiga/celery.py", line 25, in <module>
    rng = random.Random(settings.SECRET_KEY)
                        ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**How can we reproduce the behavior**

  Could reproduce with the following command in Fedora Workstation 40, and Fedora Server 39 and 40:
  podman run --name=taiga-back --rm -e SECRET_KEY=12345 docker.io/taigaio/taiga-back:latest

**Workarounds**

Haven't found one.

**Screenshots**

**Taiga environment**

  Running self-hosted with Fedora 39 and 40, on 3 separate machines using podman. Spinning the containers manually, with podman-compose and docker-compose, as well as quadlet generated systemd units.

**Desktop (please complete the following information):**
 - **OS:** Fedora Workstation 40
 - **Browser:** NA
 - **Version:** NA

**Additional context**
Changing the entrypoint and issuing a command to printenv shows me the following:

```
podman run --name=taiga-back --rm -e SECRET_KEY=12345 --entrypoint '' docker.io/taigaio/taiga-back:latest printenv
PYTHON_GET_PIP_SHA256=ee09098395e42eb1f82ef4acb231a767a6ae85504a9cf9983223df0a7cbd35d7
PYTHONUNBUFFERED=1
DEBIAN_FRONTEND=noninteractive
DJANGO_SETTINGS_MODULE=settings.config
GOSU_VERSION=1.12
PYTHONFAULTHANDLER=1
PYTHON_PIP_VERSION=24.0
container=podman
PYTHON_VERSION=3.11.9
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/e03e1607ad60522cf34a92e834138eb89f57667c/public/get-pip.py
PATH=/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SECRET_KEY=12345
PYTHONDONTWRITEBYTECODE=1
PYTHON_SETUPTOOLS_VERSION=65.5.1
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
LANG=C.UTF-8
HOME=/root
HOSTNAME=8c81ed292dd4
```

**Comment by johnyc90** [comment]
Actually my bad, converting to podman I've missed that the variable is actually named differently in the container. Setting it to TAIGA_SECRET_KEY was what I was missing
